version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop
    ports:
      - "3456:3456"
      - "9292:9292"
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
